import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/core/index.ts',
    'src/math/index.ts',
    'src/date/index.ts',
    'src/collection/index.ts',
    'src/string/index.ts',
    'src/async/index.ts',
    'src/io/index.ts',
    'src/type/index.ts',
    'src/crypto/index.ts',
    'src/path/index.ts',
    'src/dep-exray/index.ts',
    'src/dep-exray/scanner/index.ts',
    'src/dep-exray/analyzer/index.ts',
    'src/dep-exray/reporter/index.ts',
    'src/dep-exray/types.ts',
    'src/dep-exray/known-mappings.ts',
    'src/dep-exray/cli.ts',
    'src/validation/index.ts',
    'src/validation/isEmail.ts',
    'src/validation/isURL.ts',
    'src/validation/isUUID.ts',
    'src/error/index.ts',
    'src/error/MultiError.ts',
    'src/error/createError.ts',
    'src/logger/index.ts',
    'src/logger/transports.ts',
    'src/color/index.ts',
    'src/nlfunction/index.ts',
    'src/nlarray/index.ts',
    'src/ml/index.ts',
    'src/stats/index.ts',
    'src/viz-data/index.ts',
    'src/events/index.ts',
    'src/cache/index.ts',
    'src/resilience/index.ts',
    'src/auth/index.ts',
    'src/schema/index.ts',
    'src/storage/index.ts',
    'src/state-machine/index.ts',
    'src/structures/index.ts',
    'src/mock/index.ts',
    'src/diff/index.ts',
    'src/queue/index.ts',
    'src/intl/index.ts',
    'src/cli/index.ts',
    'src/geo/index.ts',
    'src/units/index.ts',
    'src/http/index.ts',
    'src/security/index.ts',
    'src/config/index.ts',
    'src/observability/index.ts',
    'src/realtime/index.ts',
    'src/serialize/index.ts',
    'src/feature-flags/index.ts',
    'src/dom/index.ts',
  ],
  format: ['esm', 'cjs'],
  dts: {
    resolve: true,
    compilerOptions: {
      noUnusedLocals: false,
      noUnusedParameters: false,
    },
  },
  clean: true,
  splitting: false,
  sourcemap: true,
  minify: false,
  target: 'es2022',
})
