import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/core/index.ts',
    'src/math/index.ts',
    'src/date/index.ts',
    'src/collection/index.ts',
    'src/string/index.ts',
    'src/async/index.ts',
    'src/io/index.ts',
    'src/type/index.ts',
    'src/crypto/index.ts',
    'src/path/index.ts',
    'src/dep-exray/index.ts',
    'src/dep-exray/scanner/index.ts',
    'src/dep-exray/analyzer/index.ts',
    'src/dep-exray/reporter/index.ts',
    'src/dep-exray/types.ts',
    'src/dep-exray/known-mappings.ts',
    'src/dep-exray/cli.ts',
    'src/validation/index.ts',
    'src/error/index.ts',
    'src/logger/index.ts',
    'src/logger/transports.ts',
    'src/color/index.ts',
    'src/nlfunction/index.ts',
    'src/nlarray/index.ts',
    'src/ml/index.ts',
    'src/stats/index.ts',
    'src/viz-data/index.ts',
  ],
  format: ['esm'],
  dts: {
    resolve: true,
    compilerOptions: {
      noUnusedLocals: false,
      noUnusedParameters: false,
    },
  },
  clean: true,
  splitting: false,
  sourcemap: true,
  minify: false,
  target: 'es2022',
})
