export { analyzeUsage } from './analyzer/index.js'
export { KNOWN_CVES, KNOWN_MAPPINGS } from './known-mappings.js'
export { generateReport } from './reporter/index.js'
export { scanProject } from './scanner/index.js'
export type { DependencyInfo, ReplacementSuggestion, ScannerConfig, ScanResult, SecurityIssue } from './types.js'
