export type { ErrorCode, ErrorCodeMap } from './createError.js'
export { createError, isTypedError, TypedError } from './createError.js'
export { collectErrors, MultiError } from './MultiError.js'
export type { ErrImpl, OkImpl, Result } from './Result.js'
export { Err, err, Ok, ok } from './Result.js'
