export type { Deferred, MemoizeAsyncOptions, QueueOptions } from './async/index.js'
export {
  allSettledMap,
  batch,
  debounceAsync,
  deferred,
  detect,
  eachSeries,
  Mutex,
  mapSeries,
  memoizeAsync,
  parallelMap,
  pipeline,
  Queue,
  RateLimiter,
  raceWithTimeout,
  retryAsync,
  Semaphore,
  sleep,
  timeout,
  waterfall,
} from './async/index.js'
export type { SortDirection } from './collection/index.js'
export {
  at,
  chunk,
  compact,
  countBy,
  deepFreeze,
  deepGet,
  deepSet,
  defaults,
  defaultsDeep,
  diff,
  difference,
  drop,
  dropRight,
  findIndex,
  findLast,
  first,
  flatten,
  fromKeys,
  fromPairs,
  groupBy,
  hasPath,
  intersection,
  invert,
  invertBy,
  isEmpty,
  keyBy,
  last,
  mapKeys,
  mapValues,
  maxBy,
  mergeWith,
  minBy,
  nth,
  omit,
  omitBy,
  orderBy,
  partition,
  pick,
  pickBy,
  pluck,
  renameKeys,
  sample,
  sampleSize,
  shuffle,
  slidingWindows,
  sortBy,
  sumBy,
  take,
  takeRight,
  toPairs,
  topoSort,
  tumblingWindows,
  union,
  uniq,
  uniqueBy,
  unset,
  unzip,
  without,
  zip,
} from './collection/index.js'
// ─── color (utilities) ──────────────────────────────────
export {
  adjustHue,
  alpha,
  complementary,
  contrastRatio,
  darken,
  desaturate,
  hexToHsl,
  hexToRgb,
  hslToHex,
  hslToRgb,
  isDark,
  isLight,
  isValidHex,
  lighten,
  meetsWCAG,
  mix,
  randomColor,
  rgba,
  rgbToHex,
  rgbToHsl,
  saturate,
} from './color/index.js'
export type {
  DebouncedFunction,
  DebounceOptions,
  MemoizedFunction,
  RetryOptions,
} from './core/index.js'
export {
  compose,
  debounce,
  deepClone,
  deepEqual,
  deepMerge,
  identity,
  memoize,
  noop,
  once,
  pipe,
  retry,
  throttle,
} from './core/index.js'
export {
  base64Decode,
  base64Encode,
  checksum,
  constantTimeEqual,
  generateOTP,
  generateToken,
  hash,
  randomHex,
  simpleHash,
  xorCipher,
} from './crypto/index.js'
export type { DateDiff, Duration } from './date/index.js'
export {
  addBusinessDays,
  addDays,
  addHours,
  addMinutes,
  addMonths,
  addSeconds,
  addYears,
  calculateAge,
  dateDiff,
  dayOfYear,
  daysInMonth,
  endOfDay,
  endOfMonth,
  endOfWeek,
  endOfYear,
  formatDate,
  formatDuration,
  formatInTimezone,
  fromUnix,
  InvalidDateError,
  isAfter,
  isBefore,
  isBetween,
  isBusinessDay,
  isEqual,
  isFuture,
  isLeapYear,
  isPast,
  isSameDay,
  isToday,
  isTomorrow,
  isWeekend,
  isYesterday,
  lastFriday,
  lastMonday,
  lastSaturday,
  lastSunday,
  lastThursday,
  lastTuesday,
  lastWednesday,
  maxDate,
  minDate,
  nextFriday,
  nextMonday,
  nextSaturday,
  nextSunday,
  nextThursday,
  nextTuesday,
  nextWednesday,
  parseDate,
  parseDuration,
  quarter,
  startOfDay,
  startOfMonth,
  startOfWeek,
  startOfYear,
  subDays,
  subMonths,
  subYears,
  timeAgo,
  timeRemaining,
  toTimezone,
  unix,
  weekOfYear,
} from './date/index.js'
export type {
  DependencyInfo,
  ReplacementSuggestion,
  ScannerConfig,
  ScanResult,
  SecurityIssue,
} from './dep-exray/index.js'
// ─── dep-exray (dependency scanner) ───────────────────────────
export {
  analyzeUsage,
  generateReport,
  KNOWN_CVES,
  KNOWN_MAPPINGS,
  scanProject,
} from './dep-exray/index.js'
export type { ErrorCode } from './error/index.js'
// ─── error (typed errors) ───────────────────────────────
export {
  collectErrors,
  createError,
  isTypedError,
  MultiError,
  TypedError,
} from './error/index.js'

export type { CsvOptions } from './io/index.js'
export {
  env,
  envArray,
  envBool,
  envInt,
  parseCsv,
  safeJsonParse,
  safeJsonStringify,
  stringifyCsv,
} from './io/index.js'
export type {
  LogLevel,
  Transport,
} from './logger/index.js'
// ─── logger (structured logging) ────────────────────────
export {
  consoleTransport,
  Logger,
  logger,
} from './logger/index.js'
export {
  createBufferedTransport,
  createConsoleTransport,
  createFileTransport,
  createJsonTransport,
} from './logger/transports.js'
export {
  add,
  approxEqual,
  average,
  ceil,
  clamp,
  combinations,
  correlation,
  DivisionByZeroError,
  div,
  factorial,
  floor,
  formatCurrency,
  gcd,
  geometricMean,
  inRange,
  isEven,
  isOdd,
  isPrime,
  lcm,
  lerp,
  mapRange,
  median,
  mode,
  mul,
  percentageOf,
  percentile,
  permutations,
  randomInt,
  range,
  round,
  sampleStddev,
  stddev,
  sub,
  sum,
  toDegrees,
  toRadians,
  weightedAverage,
} from './math/index.js'
// ─── ml (machine learning) ─────────────────────────────
export {
  accuracyScore,
  confusionMatrix,
  cosineSimilarity,
  euclideanDistance,
  KMeans,
  KNN,
  LabelEncoder,
  LinearRegression,
  MinMaxScaler,
  manhattanDistance,
  meanAbsoluteError,
  meanSquaredError,
  r2Score,
  StandardScaler,
  trainTestSplit,
} from './ml/index.js'
// ─── nlarray (NumPy-like NDArray) ──────────────────────
export { cos, exp, log, NDArray, sin, sqrt } from './nlarray/index.js'
// ─── nlfunction (functional programming) ────────────────
export {
  after,
  apply,
  attempt,
  before,
  comparing,
  constant,
  converge,
  curry,
  curryRight,
  flip,
  flow,
  id,
  ifElse,
  memoizeLast,
  memoizeSync,
  negate,
  over,
  partial,
  partialRight,
  property,
  tap,
  trace,
  tryCatch,
  unless,
  when,
  wrapArray,
} from './nlfunction/index.js'
export type { ParsedPath } from './path/index.js'
export {
  basename,
  dirname,
  extname,
  format,
  isAbsolute,
  join,
  normalize,
  parse,
  relative,
  resolve,
} from './path/index.js'
// ─── stats (statistics) ────────────────────────────────
export {
  binomialPMF,
  covariance,
  erf,
  gammaLn,
  iqr,
  kurtosis,
  normalCDF,
  normalPDF,
  pearsonCorrelation,
  poissonPMF,
  quantile,
  skewness,
  spearmanCorrelation,
  ttestInd,
} from './stats/index.js'
export {
  camelCase,
  capitalize,
  charCount,
  chars,
  countOccurrences,
  dedent,
  escapeHtml,
  escapeRegExp,
  formatBytes,
  fuzzyMatch,
  isAnagram,
  isPalindrome,
  kebabCase,
  levenshtein,
  lines,
  lowerCase,
  lowerFirst,
  maskString,
  nanoid,
  pad,
  padEnd,
  padStart,
  pascalCase,
  pluralize,
  randomBoolean,
  randomString,
  reverse,
  similarity,
  slugify,
  snakeCase,
  startCase,
  stripHtml,
  swapCase,
  template,
  toCobolCase,
  trim,
  trimEnd,
  trimStart,
  truncate,
  truncateWords,
  unescapeHtml,
  upperCase,
  upperFirst,
  uuid,
  wordCount,
  words,
} from './string/index.js'
export {
  assertDefined,
  assertType,
  castArray,
  ensureArray,
  getType,
  isArguments,
  isArray,
  isBoolean,
  isDataView,
  isDate,
  isError,
  isFunction,
  isMap,
  isNil,
  isNull,
  isNumber,
  isObject,
  isPlainObject,
  isPromise,
  isRegExp,
  isSet,
  isString,
  isSymbol,
  isTypedArray,
  isUndefined,
  isWeakMap,
  isWeakSet,
} from './type/index.js'
// ─── validation ────────────────────────────────────────
export {
  isAlpha,
  isAlphanumeric,
  isBase64,
  isCreditCard,
  isEmail,
  isFloat,
  isHexadecimal,
  isInt,
  isIP,
  isIPv4,
  isIPv6,
  isJSON,
  isLength,
  isNumeric,
  isPhone,
  isPort,
  isSlug,
  isStrongPassword,
  isURL,
  isUUID,
  matches,
} from './validation/index.js'
// ─── viz-data (visualization data) ─────────────────────
export {
  boxPlotData,
  colorMap,
  ecdf,
  freedmanDiaconisBins,
  histogram,
  kde,
  sturgesBins,
} from './viz-data/index.js'
