export type { Deferred, MemoizeAsyncOptions, QueueOptions } from './async/index.js'
export {
  allSettledMap,
  batch,
  debounceAsync,
  deferred,
  detect,
  eachSeries,
  Mutex,
  mapSeries,
  memoizeAsync,
  parallelMap,
  pipeline,
  Queue,
  RateLimiter,
  raceWithTimeout,
  retryAsync,
  Semaphore,
  sleep,
  timeout,
  waterfall,
} from './async/index.js'
// ─── auth (JWT/PKCE) ─────────────────────────────────────
export { decodeJWT, generatePKCE, parseBasicAuth, signJWT, verifyJWT } from './auth/index.js'
// ─── cache (LRU/LFU/TTL) ──────────────────────────────────
export { type CacheStats, CacheStatsCollector, LFUCache, LRUCache, memoizeWithCache, TTLCache } from './cache/index.js'
// ─── cli (CLI building blocks) ───────────────────────────
export {
  type ArgOption,
  type ArgSpec,
  colorize,
  confirm,
  type ParsedArgs,
  parseArgs,
  prompt,
  renderTable,
  Spinner,
  type TableColumn,
  type TableOptions,
} from './cli/index.js'
export type { SortDirection } from './collection/index.js'
export {
  at,
  chunk,
  compact,
  countBy,
  deepFreeze,
  deepGet,
  deepSet,
  defaults,
  defaultsDeep,
  diff,
  difference,
  drop,
  dropRight,
  findIndex,
  findLast,
  first,
  flatten,
  fromKeys,
  fromPairs,
  groupBy,
  hasPath,
  intersection,
  invert,
  invertBy,
  isEmpty,
  keyBy,
  last,
  mapKeys,
  mapValues,
  maxBy,
  mergeWith,
  minBy,
  nth,
  omit,
  omitBy,
  orderBy,
  paginate,
  partition,
  pick,
  pickBy,
  pluck,
  renameKeys,
  rotate,
  sample,
  sampleSize,
  shuffle,
  slidingWindows,
  sortBy,
  sumBy,
  take,
  takeRight,
  toPairs,
  topoSort,
  transpose,
  tumblingWindows,
  union,
  uniq,
  uniqueBy,
  unset,
  unzip,
  without,
  zip,
} from './collection/index.js'
// ─── color (utilities) ──────────────────────────────────
export {
  adjustHue,
  alpha,
  complementary,
  contrastRatio,
  darken,
  desaturate,
  hexToHsl,
  hexToRgb,
  hslToHex,
  hslToRgb,
  isDark,
  isLight,
  isValidHex,
  lighten,
  meetsWCAG,
  mix,
  randomColor,
  rgba,
  rgbToHex,
  rgbToHsl,
  saturate,
} from './color/index.js'
export type { ConfigSource, LoadConfigOptions } from './config/index.js'
// ─── config (layered configuration) ────────────────────────
export { cliSource, envSource, fileSource, loadConfig, maskSecrets, watchConfig } from './config/index.js'
export type {
  DebouncedFunction,
  DebounceOptions,
  MemoizedFunction,
  RetryOptions,
} from './core/index.js'
export {
  compose,
  debounce,
  deepClone,
  deepEqual,
  deepMerge,
  identity,
  memoize,
  noop,
  once,
  pipe,
  retry,
  throttle,
} from './core/index.js'
export {
  base64Decode,
  base64Encode,
  checksum,
  constantTimeEqual,
  generateOTP,
  generateToken,
  hash,
  randomHex,
  sha256,
  sha512,
  simpleHash,
  xorCipher,
} from './crypto/index.js'
export type { DateDiff, Duration } from './date/index.js'
export {
  addBusinessDays,
  addDays,
  addHours,
  addMinutes,
  addMonths,
  addSeconds,
  addYears,
  calculateAge,
  dateDiff,
  dayOfYear,
  daysInMonth,
  endOfDay,
  endOfMonth,
  endOfWeek,
  endOfYear,
  formatDate,
  formatDuration,
  formatInTimezone,
  fromUnix,
  getHolidays,
  humanizeDuration,
  InvalidDateError,
  isAfter,
  isBefore,
  isBetween,
  isBusinessDay,
  isEqual,
  isFuture,
  isLeapYear,
  isPast,
  isSameDay,
  isToday,
  isTomorrow,
  isWeekend,
  isYesterday,
  lastFriday,
  lastMonday,
  lastSaturday,
  lastSunday,
  lastThursday,
  lastTuesday,
  lastWednesday,
  maxDate,
  minDate,
  nextFriday,
  nextMonday,
  nextSaturday,
  nextSunday,
  nextThursday,
  nextTuesday,
  nextWednesday,
  parseDate,
  parseDuration,
  quarter,
  startOfDay,
  startOfMonth,
  startOfWeek,
  startOfYear,
  subDays,
  subMonths,
  subYears,
  timeRemaining,
  toTimezone,
  unix,
  weekOfYear,
} from './date/index.js'
export type {
  DependencyInfo,
  ReplacementSuggestion,
  ScannerConfig,
  ScanResult,
  SecurityIssue,
} from './dep-exray/index.js'
// ─── dep-exray (dependency scanner) ───────────────────────────
export {
  analyzeUsage,
  generateReport,
  KNOWN_CVES,
  KNOWN_MAPPINGS,
  scanProject,
} from './dep-exray/index.js'
// ─── diff (text & object diff) ───────────────────────────
export { type DiffChunk, type ObjectDiffResult, objectDiff, patch, textDiff, unifiedDiff } from './diff/index.js'
// ─── dom (browser utilities) ──────────────────────────────
export {
  copyToClipboard,
  debounceResize,
  downloadFile,
  getViewport,
  isTouchDevice,
  lockScroll,
  onClickOutside,
  onVisible,
  readFileAsDataURL,
  readFileAsText,
  scrollToElement,
  scrollToTop,
  trapFocus,
} from './dom/index.js'
export type { ErrImpl, ErrorCode, OkImpl, Result } from './error/index.js'
// ─── error (typed errors + result type) ─────────────────
export {
  collectErrors,
  createError,
  Err,
  err,
  isTypedError,
  MultiError,
  Ok,
  ok,
  TypedError,
} from './error/index.js'
// ─── events (typed EventEmitter) ──────────────────────────
export { createPubSub, EventBus, EventEmitter, type WildcardPayload } from './events/index.js'
// ─── feature-flags ─────────────────────────────────────────
export {
  bucketUser,
  createFlagStore,
  type FlagDefinition,
  type FlagStore,
  type FlagStoreOptions,
  hashString,
} from './feature-flags/index.js'
// ─── geo (geospatial utilities) ──────────────────────────
export { boundingBox, type Coord, decodeGeohash, geohash, haversineDistance, isPointInPolygon, midpoint, toDMS } from './geo/index.js'
// ─── http (HTTP client) ────────────────────────────────────
export {
  createHttpClient,
  type HttpClient,
  type HttpClientOptions,
  HttpError,
  type HttpResponse,
  type Interceptor,
  type RateLimitMiddlewareOptions,
} from './http/index.js'
// ─── intl (internationalization) ─────────────────────────
export { createTranslator, formatCurrency, formatList, formatNumber, formatRelativeTime, pluralize, timeAgo } from './intl/index.js'
export type { CsvOptions } from './io/index.js'
export {
  env,
  envArray,
  envBool,
  envInt,
  parseCsv,
  readJSONFile,
  safeJsonParse,
  safeJsonStringify,
  stringifyCsv,
  watchFile,
  writeJSONFile,
} from './io/index.js'
export type {
  LogLevel,
  Transport,
} from './logger/index.js'
// ─── logger (structured logging) ────────────────────────
export {
  consoleTransport,
  Logger,
  logger,
} from './logger/index.js'
export {
  createBufferedTransport,
  createConsoleTransport,
  createFileTransport,
  createJsonTransport,
} from './logger/transports.js'
export {
  add,
  approxEqual,
  average,
  ceil,
  clamp,
  combinations,
  correlation,
  DivisionByZeroError,
  div,
  factorial,
  floor,
  gcd,
  geometricMean,
  inRange,
  isEven,
  isOdd,
  isPrime,
  lcm,
  lerp,
  mapRange,
  median,
  mode,
  mul,
  percentageOf,
  percentile,
  permutations,
  randomInt,
  range,
  round,
  sampleStddev,
  stddev,
  sub,
  sum,
  toDegrees,
  toRadians,
  weightedAverage,
} from './math/index.js'
// ─── ml (machine learning) ─────────────────────────────
export {
  accuracyScore,
  confusionMatrix,
  cosineSimilarity,
  crossValScore,
  euclideanDistance,
  KMeans,
  KNN,
  kFold,
  LabelEncoder,
  LinearRegression,
  LogisticRegression,
  MinMaxScaler,
  manhattanDistance,
  meanAbsoluteError,
  meanSquaredError,
  OneHotEncoder,
  PCA,
  r2Score,
  StandardScaler,
  trainTestSplit,
} from './ml/index.js'
// ─── mock (fake data generator) ──────────────────────────
export {
  fakeAddress,
  fakeAvatar,
  fakeBoolean,
  fakeCity,
  fakeColor,
  fakeCompany,
  fakeDate,
  fakeDepartment,
  fakeEmail,
  fakeFirstName,
  fakeFloat,
  fakeFromSchema,
  fakeFullName,
  fakeInt,
  fakeJobTitle,
  fakeLastName,
  fakeLorem,
  fakeName,
  fakeParagraph,
  fakePhone,
  fakeSentence,
  fakeStreet,
  fakeUrl,
  fakeUUID,
  seedRandom,
} from './mock/index.js'
// ─── nlarray (NumPy-like NDArray) ──────────────────────
export { cos, exp, log, NDArray, sin, sqrt } from './nlarray/index.js'
// ─── nlfunction (functional programming) ────────────────
export {
  after,
  apply,
  attempt,
  before,
  comparing,
  constant,
  converge,
  curry,
  curryRight,
  flip,
  flow,
  id,
  ifElse,
  memoizeLast,
  memoizeSync,
  negate,
  over,
  partial,
  partialRight,
  property,
  tap,
  trace,
  tryCatch,
  unless,
  when,
  wrapArray,
} from './nlfunction/index.js'
// ─── observability (metrics & tracing) ─────────────────────
export {
  Counter,
  Gauge,
  getCorrelationId,
  Histogram,
  MetricsRegistry,
  type Span,
  type SpanTreeNode,
  setCorrelationId,
  Tracer,
  toOTLPJson,
  withCorrelationId,
} from './observability/index.js'
export type { ParsedPath } from './path/index.js'
export {
  basename,
  dirname,
  extname,
  format,
  isAbsolute,
  join,
  normalize,
  parse,
  relative,
  resolve,
} from './path/index.js'
export type { Job, JobQueueOptions } from './queue/index.js'
// ─── queue (job queue & scheduling) ──────────────────────
export { cron, Debouncer, JobQueue, scheduleEvery } from './queue/index.js'
// ─── reactive (signals, computed, effects) ─────────────────
export { type Computed, computed, type Effect, effect, type Signal, signal } from './reactive/index.js'
// ─── realtime (WebSocket & SSE) ────────────────────────────
export {
  createSSEClient,
  createWSClient,
  type SSEClient,
  type SSEClientOptions,
  type WSClient,
  type WSClientOptions,
} from './realtime/index.js'
// ─── resilience (circuit breaker, bulkhead, retry) ────────
export {
  Bulkhead,
  CircuitBreaker,
  type CircuitBreakerOptions,
  type CircuitState,
  Fallback,
  type RetryWithBackoffOptions,
  retryWithBackoff,
  Timeout,
} from './resilience/index.js'
// ─── schema (zod-lite) ────────────────────────────────────
export {
  ArraySchema,
  BooleanSchema,
  EnumSchema,
  type Infer,
  LiteralSchema,
  NullableSchema,
  NumberSchema,
  ObjectSchema,
  OptionalSchema,
  Schema,
  StringSchema,
  s,
  ValidationError,
} from './schema/index.js'
// ─── security (sanitization & hardening) ───────────────────
export { createRateLimiter, csrfToken, detectSecrets, maskPII, type SecretMatch, sanitizeHtml, verifyCsrfToken } from './security/index.js'
// ─── serialize (MessagePack, binary) ───────────────────────
export {
  BufferReader,
  BufferWriter,
  decodeBase58,
  decodeBase62,
  decodeMsgPack,
  encodeBase58,
  encodeBase62,
  encodeMsgPack,
} from './serialize/index.js'
// ─── state-machine (FSM) ─────────────────────────────────
export { createMachine, type Machine, type MachineConfig, type MachineContext } from './state-machine/index.js'
// ─── stats (statistics) ────────────────────────────────
export {
  anovaOneWay,
  binomialPMF,
  chiSquareGoodnessOfFit,
  chiSquareTest,
  covariance,
  erf,
  gammaLn,
  iqr,
  kurtosis,
  mannWhitneyU,
  normalCDF,
  normalPDF,
  pearsonCorrelation,
  poissonPMF,
  quantile,
  skewness,
  spearmanCorrelation,
  ttestInd,
} from './stats/index.js'
// ─── storage (universal storage wrapper) ──────────────────
export {
  type CookieDriverOptions,
  cookieDriver,
  createStorage,
  localStorageDriver,
  memoryDriver,
  Storage,
  type StorageDriver,
  type StorageOptions,
  sessionStorageDriver,
} from './storage/index.js'
export {
  camelCase,
  capitalize,
  charCount,
  chars,
  countOccurrences,
  dedent,
  diacriticsRemove,
  escapeHtml,
  escapeRegExp,
  formatBytes,
  fuzzyMatch,
  highlightMatches,
  isAnagram,
  isPalindrome,
  kebabCase,
  levenshtein,
  lines,
  lowerCase,
  lowerFirst,
  maskString,
  nanoid,
  pad,
  padEnd,
  padStart,
  pascalCase,
  randomBoolean,
  randomString,
  reverse,
  similarity,
  slugify,
  snakeCase,
  startCase,
  stripHtml,
  swapCase,
  template,
  toCobolCase,
  toTitleCase,
  trim,
  trimEnd,
  trimStart,
  truncate,
  truncateWords,
  unescapeHtml,
  upperCase,
  upperFirst,
  uuid,
  wordCount,
  words,
  wrap,
} from './string/index.js'
// ─── structures (Trie, Graph, Heap, Monads, etc) ────────
export {
  BloomFilter,
  Deque,
  DisjointSet,
  Either,
  Graph,
  Heap,
  LinkedList,
  Maybe,
  PriorityQueue,
  Trie,
} from './structures/index.js'
// ─── template (mustache-compatible template engine) ────────
export { compile, render } from './template/index.js'
export {
  assertDefined,
  assertType,
  castArray,
  ensureArray,
  getType,
  isArguments,
  isArray,
  isBoolean,
  isDataView,
  isDate,
  isError,
  isFunction,
  isMap,
  isNil,
  isNull,
  isNumber,
  isObject,
  isPlainObject,
  isPromise,
  isRegExp,
  isSet,
  isString,
  isSymbol,
  isTypedArray,
  isUndefined,
  isWeakMap,
  isWeakSet,
} from './type/index.js'
// ─── units (unit conversion) ─────────────────────────────
export { convert, convertWithCategory, getUnitCategory, isConvertible, UNIT_CATEGORIES } from './units/index.js'
// ─── validation ────────────────────────────────────────
export {
  isAlpha,
  isAlphanumeric,
  isBase64,
  isCreditCard,
  isCronExpression,
  isEmail,
  isFloat,
  isHexadecimal,
  isIBAN,
  isInt,
  isIP,
  isIPv4,
  isIPv6,
  isISBN,
  isJSON,
  isJWT,
  isLatLng,
  isLength,
  isMACAddress,
  isNumeric,
  isPhone,
  isPort,
  isSemVer,
  isSlug,
  isStrongPassword,
  isURL,
  isUUID,
  matches,
} from './validation/index.js'
export type {
  BarChartData,
  LineChartData,
  PieChartData,
  ScatterChartData,
  SvgChartOptions,
} from './viz-data/index.js'
// ─── viz-data (visualization data) ─────────────────────
export {
  boxPlotData,
  colorMap,
  ecdf,
  freedmanDiaconisBins,
  histogram,
  kde,
  sturgesBins,
  svgBarChart,
  svgLineChart,
  svgPieChart,
  svgScatterChart,
} from './viz-data/index.js'
